<a href="https://colab.research.google.com/github/jesung/Tic-Tac-Toe/blob/master/Copy_of_tic_tac_toe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pprint
import numpy as np
import tensorflow as tf
from tensorflow import keras
import random

model = keras.models.Sequential([
    keras.layers.Dense(32, activation=tf.nn.relu, input_shape=(1,9)),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(16, activation=tf.nn.relu),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(1, activation=tf.nn.sigmoid)
])

model.compile(optimizer='adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy','binary_crossentropy'])

class tic_tac_toe:
    def __init__(self):
        self.board = np.array([[0,0,0],[0,0,0],[0,0,0]])
        self.turn = 1

    def reset(self):
        self.board = np.array([[0,0,0],[0,0,0],[0,0,0]])
        self.turn = 1

    def move(self,x,y):
        ##### need to update #######
        if self.board[x,y] != 0:   
            print('Invalid move',x,y)
            print(self.board)
        else:
            self.board[x,y] = self.turn
            self.turn = -1 * self.turn

def win(board):
    for i in range(3):
        if board[0,i]==board[1,i]==board[2,i]!=0:
            return 'Won'
        if board[i,0]==board[i,1]==board[i,2]!=0:
            return 'Won'

    if board[0,0]==board[1,1]==board[2,2]!=0:
        return 'Won'
    if board[0,2]==board[1,1]==board[2,0]!=0:
        return 'Won'

    if not 0 in board:
        return 'Drawn'
    else:
        return 'In-Progress'
          
def move_gen(board_state, turn):
    legal_moves = {}
    
    for i in range(3):
        for j in range(3):
            if board_state[i,j] == 0:
                tmp_board = board_state.copy()
                tmp_board[i,j] = turn
                legal_moves[(i,j)]=tmp_board.flatten()

    return legal_moves
  
def move_sel(move_list, turn, train=True):
    tmp = np.zeros((9,12))
    i = 0

    for key, value in move_list.items():
      tmp[i,0:9] = value.reshape(1,9)
      tmp[i,9] = model.predict(value.reshape(1,1,9))[0][0][0]
      tmp[i,10:12] = [key[0], key[1]]
      #print(tmp[i,9], (tmp[i,10],tmp[i,11]))
      
      #if win(value.reshape(3,3)) == 'Win':
      #    return tmp[i,0:9], tmp[i,9], (tmp[i,10],tmp[i,11])
      i = i + 1
    
    if random.randint(1,5) == train:
      #if turn == 0:
        #j = random.choices(range(i),tmp[:i,9]**1)
      #else:  
        #j = random.choices(range(i),(1-tmp[:i,9])**1)
      j = random.randint(0,i-1)
    else:
      if turn == 1:
        j = np.argmax(tmp[:i,9])
      else:
        j = np.argmin(tmp[:i,9])
    
    return tmp[j,0:9], tmp[j,9], (tmp[j,10],tmp[j,11])

def simulate(batch_size, num_round):
  for i in range(num_round):
    board, prob, move = move_sel(move_gen(game.board, game.turn), game.turn)
    train = [np.append(board,prob)]
    result = [0,0,0]
    
    for j in range(batch_size):
      #clean up - train & tmp outside for loops and clear at beginning
      board, prob, move = move_sel(move_gen(game.board, game.turn), game.turn)
      tmp = [np.append(board,prob)]
      
      while win(game.board) == 'In-Progress':
        board, prob, move = move_sel(move_gen(game.board, game.turn), game.turn)
        tmp = np.append(tmp, [np.append(board,prob)], axis = 0)
        
        #print(move[0], move[1])
        game.move(int(move[0]), int(move[1]))

      #update score based on result
      if win(game.board) == 'Won':
          tmp[:,-1] = (1-game.turn)/2
          if game.turn == -1:
              result[0] = result[0] + 1        
          else:
              result[1] = result[1] + 1        
      else:
          tmp[:,-1] = 0.5
          result[2] = result[2] + 1
      
      #add to training set
      train = np.append(train, tmp, axis = 0)
            
      game.reset()
    
    #print(train.shape)
    #print(train)
    print('Round', i)
    model.fit(train[:,0:9].reshape(-1,1,9), train[:,9].reshape(-1,1,1),epochs=3,verbose=0)
    print(result[0],'-',result[1],'-',result[2])

In [0]:
game = tic_tac_toe()

simulate(500,400)



Round 0
338 - 129 - 33
Round 1
366 - 110 - 24
Round 2
174 - 276 - 50
Round 3
382 - 99 - 19
Round 4
160 - 319 - 21
Round 5
309 - 135 - 56
Round 6
389 - 79 - 32
Round 7
322 - 124 - 54
Round 8
367 - 57 - 76
Round 9
186 - 266 - 48
Round 10
328 - 122 - 50
Round 11
203 - 254 - 43
Round 12
344 - 94 - 62
Round 13
159 - 148 - 193
Round 14
209 - 69 - 222
Round 15
346 - 80 - 74
Round 16
197 - 254 - 49
Round 17
146 - 113 - 241
Round 18
183 - 261 - 56
Round 19
302 - 124 - 74
Round 20
336 - 115 - 49
Round 21
160 - 273 - 67
Round 22
366 - 73 - 61
Round 23
181 - 64 - 255
Round 24
214 - 93 - 193
Round 25
225 - 91 - 184
Round 26
332 - 106 - 62
Round 27
167 - 109 - 224
Round 28
370 - 56 - 74
Round 29
328 - 85 - 87
Round 30
377 - 38 - 85
Round 31
157 - 229 - 114
Round 32
376 - 52 - 72
Round 33
388 - 29 - 83
Round 34
391 - 47 - 62
Round 35
360 - 79 - 61
Round 36
212 - 47 - 241
Round 37
208 - 70 - 222
Round 38
179 - 59 - 262
Round 39
333 - 78 - 89
Round 40
193 - 35 - 272
Round 41
218 - 62 - 220
Round 42
350

In [0]:
def move_sel(move_list, turn, train=True):
    tmp = np.zeros((9,12))
    i = 0

    for key, value in move_list.items():
      tmp[i,0:9] = value.reshape(1,9)
      tmp[i,9] = model.predict(value.reshape(1,1,9))[0][0][0]
      tmp[i,10:12] = [key[0], key[1]]
      print(tmp[i,9], (tmp[i,10],tmp[i,11]))
      #if win(value.reshape(3,3)) == 'Win':
      #    return tmp[i,0:9], tmp[i,9], (tmp[i,10],tmp[i,11])
      i = i + 1
    
    if random.randint(1,5) == train:
      #if turn == 0:
        #j = random.choices(range(i),tmp[:i,9]**1)
      #else:  
        #j = random.choices(range(i),(1-tmp[:i,9])**1)
      j = random.randint(0,i-1)
    else:
      if turn == 1:
        j = np.argmax(tmp[:i,9])
      else:
        j = np.argmin(tmp[:i,9])
    
    return tmp[j,0:9], tmp[j,9], (tmp[j,10],tmp[j,11])

In [40]:
#game.reset()
game.move(1,0)
print(win(game.board))
print(game.board)
print(game.turn)
print(move_sel(move_gen(game.board, game.turn), game.turn, train=False))


In-Progress
[[ 1 -1 -1]
 [ 0  1  1]
 [ 0  1 -1]]
-1
0.5613197088241577 (1.0, 0.0)
0.9638458490371704 (2.0, 0.0)
(array([ 1., -1., -1., -1.,  1.,  1.,  0.,  1., -1.]), 0.5613197088241577, (1.0, 0.0))
