<a href="https://colab.research.google.com/github/jesung/Tic-Tac-Toe/blob/master/tic_tac_toe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pprint
import numpy as np
import tensorflow as tf
from tensorflow import keras
import random

model = keras.models.Sequential([
    keras.layers.Dense(32, activation=tf.nn.relu, input_shape=(1,9)),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(16, activation=tf.nn.relu),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(1, activation=tf.nn.sigmoid)
])

model.compile(optimizer='adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy','binary_crossentropy'])

class tic_tac_toe:
    def __init__(self):
        self.board = np.array([[0,0,0],[0,0,0],[0,0,0]])
        self.turn = 1

    def reset(self):
        self.board = np.array([[0,0,0],[0,0,0],[0,0,0]])
        self.turn = 1

    def move(self,x,y):
        ##### need to update #######
        if self.board[x,y] != 0:   
            print('Invalid move',x,y)
            print(self.board)
        else:
            self.board[x,y] = self.turn
            self.turn = -1 * self.turn

def win(board):
    for i in range(3):
        if board[0,i]==board[1,i]==board[2,i]!=0:
            return 'Won'
        if board[i,0]==board[i,1]==board[i,2]!=0:
            return 'Won'

    if board[0,0]==board[1,1]==board[2,2]!=0:
        return 'Won'
    if board[0,2]==board[1,1]==board[2,0]!=0:
        return 'Won'

    if not 0 in board:
        return 'Drawn'
    else:
        return 'In-Progress'
          
def move_gen(board_state, turn):
    legal_moves = {}
    
    for i in range(3):
        for j in range(3):
            if board_state[i,j] == 0:
                tmp_board = board_state.copy()
                tmp_board[i,j] = turn
                legal_moves[(i,j)]=tmp_board.flatten()

    return legal_moves
  
def move_sel(move_list, turn, train=True):
    tmp = np.zeros((9,12))
    i = 0

    for key, value in move_list.items():
      tmp[i,0:9] = value.reshape(1,9)
      tmp[i,9] = model.predict(value.reshape(1,1,9))[0][0][0]
      tmp[i,10:12] = [key[0], key[1]]
      if not train:
          print(tmp[i,9], (tmp[i,10],tmp[i,11]))
      
      #if win(value.reshape(3,3)) == 'Win':
      #    return tmp[i,0:9], tmp[i,9], (tmp[i,10],tmp[i,11])
      i = i + 1
    
    if random.randint(1,5) == train:
      #if turn == 0:
        #j = random.choices(range(i),tmp[:i,9]**1)
      #else:  
        #j = random.choices(range(i),(1-tmp[:i,9])**1)
      j = random.randint(0,i-1)
    else:
      if turn == 1:
        j = np.argmax(tmp[:i,9])
      else:
        j = np.argmin(tmp[:i,9])
    
    return tmp[j,0:9], tmp[j,9], (tmp[j,10],tmp[j,11])

def simulate(batch_size, num_round):
  for i in range(num_round):
    board, prob, move = move_sel(move_gen(game.board, game.turn), game.turn)
    train = [np.append(board,prob)]
    result = [0,0,0]
    
    for j in range(batch_size):
      #clean up - train & tmp outside for loops and clear at beginning
      board, prob, move = move_sel(move_gen(game.board, game.turn), game.turn)
      tmp = [np.append(board,prob)]
      
      while win(game.board) == 'In-Progress':
        board, prob, move = move_sel(move_gen(game.board, game.turn), game.turn)
        tmp = np.append(tmp, [np.append(board,prob)], axis = 0)
        
        #print(move[0], move[1])
        game.move(int(move[0]), int(move[1]))

      #update score based on result
      if win(game.board) == 'Won':
          tmp[:,-1] = (1-game.turn)/2
          if game.turn == -1:
              result[0] = result[0] + 1        
          else:
              result[1] = result[1] + 1        
      else:
          tmp[:,-1] = 0.5
          result[2] = result[2] + 1
      
      #add to training set
      train = np.append(train, tmp, axis = 0)
            
      game.reset()
    
    #print(train.shape)
    #print(train)
    print('Round', i)
    model.fit(train[:,0:9].reshape(-1,1,9), train[:,9].reshape(-1,1,1),epochs=3,verbose=0)
    print(result[0],'-',result[1],'-',result[2])

In [11]:
game = tic_tac_toe()

simulate(250,400)



Round 0
196 - 43 - 11
Round 1
100 - 40 - 110
Round 2
52 - 165 - 33
Round 3
91 - 32 - 127
Round 4
193 - 31 - 26
Round 5
101 - 52 - 97
Round 6
99 - 28 - 123
Round 7
113 - 56 - 81
Round 8
79 - 142 - 29
Round 9
102 - 32 - 116
Round 10
161 - 36 - 53
Round 11
161 - 43 - 46
Round 12
112 - 63 - 75
Round 13
167 - 38 - 45
Round 14
70 - 63 - 117
Round 15
72 - 60 - 118
Round 16
181 - 32 - 37
Round 17
188 - 36 - 26
Round 18
84 - 116 - 50
Round 19
182 - 46 - 22
Round 20
168 - 50 - 32
Round 21
180 - 44 - 26
Round 22
86 - 39 - 125
Round 23
168 - 50 - 32
Round 24
91 - 135 - 24
Round 25
84 - 63 - 103
Round 26
153 - 29 - 68
Round 27
97 - 110 - 43
Round 28
130 - 34 - 86
Round 29
79 - 127 - 44
Round 30
170 - 31 - 49
Round 31
95 - 38 - 117
Round 32
123 - 24 - 103
Round 33
88 - 27 - 135
Round 34
101 - 25 - 124
Round 35
79 - 23 - 148
Round 36
80 - 25 - 145
Round 37
74 - 53 - 123
Round 38
91 - 28 - 131
Round 39
94 - 48 - 108
Round 40
97 - 15 - 138
Round 41
103 - 37 - 110
Round 42
96 - 43 - 111
Round 43
106 - 2

KeyboardInterrupt: ignored

In [22]:
game.reset()
#game.move(2,0)
print(win(game.board))
print(game.board)
print(game.turn)
print(move_sel(move_gen(game.board, game.turn), game.turn, train=False))


In-Progress
[[0 0 0]
 [0 0 0]
 [0 0 0]]
1
0.5798814296722412 (0.0, 0.0)
0.5475069284439087 (0.0, 1.0)
0.5662556886672974 (0.0, 2.0)
0.5463427901268005 (1.0, 0.0)
0.591604471206665 (1.0, 1.0)
0.5475069284439087 (1.0, 2.0)
0.5902537703514099 (2.0, 0.0)
0.5475069284439087 (2.0, 1.0)
0.5787570476531982 (2.0, 2.0)
(array([0., 0., 0., 0., 1., 0., 0., 0., 0.]), 0.591604471206665, (1.0, 1.0))
