<a href="https://colab.research.google.com/github/jesung/Tic-Tac-Toe/blob/master/tic_tac_toe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pprint
import numpy as np
import tensorflow as tf
from tensorflow import keras
import random

model = keras.models.Sequential([
    keras.layers.Dense(18, activation=tf.nn.relu, input_shape=(1,9)),
    keras.layers.Dropout(0.1),
    keras.layers.Dense(9, activation=tf.nn.relu),
    keras.layers.Dropout(0.1),
    keras.layers.Dense(1, activation=tf.nn.sigmoid)
])

model.compile(optimizer='adam',
                  loss='binary_crossentropy',
                  metrics=['accuracy','binary_crossentropy'])

class tic_tac_toe:
    def __init__(self):
        self.board = np.array([[2,2,2],[2,2,2],[2,2,2]])
        self.turn = 0

    def reset(self):
        self.board = np.array([[2,2,2],[2,2,2],[2,2,2]])
        self.turn = 0

    def move(self,x,y):
        ##### need to update #######
        if self.board[x,y] != 2:   
            print('Invalid move',x,y)
            print(self.board)
        else:
            self.board[x,y] = self.turn
            
            if self.turn == 0:
                self.turn = 1
            else:
                self.turn = 0

    def win(self):
        for i in range(3):
            if self.board[0,i]==self.board[1,i]==self.board[2,i]<2:
                return 'Won'
            if self.board[i,0]==self.board[i,1]==self.board[i,2]<2:
                return 'Won'

        if self.board[0,0]==self.board[1,1]==self.board[2,2]<2:
            return 'Won'
        if self.board[0,2]==self.board[1,1]==self.board[0,2]<2:
            return 'Won'

        if not 2 in self.board:
            return 'Drawn'
        else:
            return 'In-Progress'

def move_gen(board_state, turn):
    legal_moves = {}
    
    for i in range(3):
        for j in range(3):
            if board_state[i,j] == 2:
                tmp_board = board_state.copy()
                tmp_board[i,j] = turn
                legal_moves[(i,j)]=tmp_board.flatten()

    return legal_moves
  
def move_sel(move_list, turn):
    tmp = np.zeros((9,12))
    i = 0

    for key, value in move_list.items():
      #print(value.reshape(1,9))
      tmp[i,0:9] = value.reshape(1,9)
      tmp[i,9] = model.predict(value.reshape(1,1,9))[0][0][0]
      tmp[i,10:12] = [key[0], key[1]]
      i = i + 1
    
    #print(tmp)
    if turn == 0:
      j = random.choices(range(i),tmp[:i,9]**3)
    else:  
      j = random.choices(range(i),(1-tmp[:i,9])**3)
      
    return tmp[j,0:9], tmp[j,9][0], (tmp[j,10][0],tmp[j,11][0])

def simulate(batch_size, num_epoch):
  for i in range(num_epoch):
    board, prob, move = move_sel(move_gen(game.board, game.turn), game.turn)
    train = [np.append(board,prob)]
    
    for j in range(batch_size):
      board, prob, move = move_sel(move_gen(game.board, game.turn), game.turn)
      tmp = [np.append(board,prob)]

      while game.win() == 'In-Progress':
        board, prob, move = move_sel(move_gen(game.board, game.turn), game.turn)
        tmp = np.append(tmp, [np.append(board,prob)], axis = 0)
        
        #print(move[0], move[1])
        game.move(int(move[0]), int(move[1]))

      #update score based on result
      if game.win() == 'Won':
        tmp[:,-1] = game.turn
      else:
        tmp[:,-1] = 0.5
      
      #add to training set
      train = np.append(train, tmp, axis = 0)
      
      game.reset()
    
    #print(train.shape)
    #print(train)
    print('Epoch', i)
    model.fit(train[:,0:9].reshape(-1,1,9), train[:,9].reshape(-1,1,1),epochs=5)

In [0]:
#model.summary()

game = tic_tac_toe()
#game.move(2,2)
#game.move(1,1)
#game.move(0,0)
#game.move(1,0)
#game.move(2,0)
#game.move(1,2)

#print(game.win())

#print(game.board)
#pprint.pprint(move_gen(game.board,game.turn))

simulate(1000,50)



In [26]:
#game.reset()
game.move(0,1)
print(game.board)
print(move_sel(move_gen(game.board, game.turn), game.turn))


[[2 1 2]
 [2 1 0]
 [0 1 0]]
(array([[2., 1., 0., 2., 1., 0., 0., 1., 0.]]), 0.7173953652381897, (0.0, 2.0))


In [0]:
game.reset()
board, prob, move = move_sel(move_gen(game.board, game.turn), game.turn)
tmp = [np.append(board,prob)]


In [0]:
while game.win() == 'In-Progress':
  board, prob, move = move_sel(move_gen(game.board, game.turn), game.turn)
  tmp = np.append(tmp, [np.append(board,prob)], axis = 0)

  #print(move[0], move[1])
  game.move(int(move[0]), int(move[1]))

In [0]:

#update score based on result
if game.win() == 'Won':
  tmp[:,-1] = game.turn
else:
  tmp[:,-1] = 0.5

#add to training set
train = np.append(train, tmp, axis = 0)

game.reset()

In [55]:
print(game.turn)
print(game.board)
print(game.win())

1
[[1 0 1]
 [0 0 1]
 [1 0 0]]
Won
